const locaciones = [
    { nombre: "plaza bolivar", precio: '10-12' },
    { nombre: "vinto centro", precio: '15' },
    { nombre: "hospitar benigno sanchez", precio: '12-15' },
    { nombre: "villa moderna", precio: '12-15' },
    { nombre: "antofagasta norte", precio: '15-20' },
    { nombre: "antofagasta sud", precio: '10-15' },
    { nombre: "antofagasta parque de aves", precio: '20' },
    { nombre: "piscina san isidro", precio: '15-20' },
    { nombre: "el paso", precio: '40' },
    { nombre: "tiquipaya", precio: '50' },
    { nombre: "kilometro 5", precio: '30' },
    { nombre: "kilometro 10", precio: '15-20' },
    { nombre: "feicobol", precio: '70' },
    { nombre: "puente beigin", precio: '35' },
    { nombre: "fexco", precio: '70' },
    { nombre: "cruce taquiña", precio: '55-60' },
    { nombre: "sacaba plaza", precio: '80-90' },
    { nombre: "sipe sipe", precio: '40' },
    { nombre: "barrio cami", precio: '40' },
    { nombre: "colegio bella vista", precio: '35' },
    { nombre: "tecnológico bella vista", precio: '40-45' },
    { nombre: "tecnológico el paso", precio: '35' },
    { nombre: "terminal cochabamba", precio: '50' },
    { nombre: "terminal quillacollo", precio: '15' },
    { nombre: "calvario quillacollo", precio: '10' },
    { nombre: "barrio esmeralda", precio: '15' },
    { nombre: "villa carmen", precio: '15' },
{ nombre: "santo domingo", precio: '10' },
{ nombre: "tiquirani", precio: '20' },
{ nombre: "loma linda", precio: '35' },
{ nombre: "berenguela", precio: '20-25' },
{ nombre: "concordia quillacollo", precio: '15' },
{ nombre: "marquina", precio: '35' },
{ nombre: "bella vista final", precio: '50' },
{ nombre: "chulla", precio: '20-30' },
{ nombre: "san jorge vinto", precio: '20-25' },
{ nombre: "vinto chico", precio: '25' },
{ nombre: "suticollo", precio: '40' },
{ nombre: "motecato", precio: '30-40' },
{ nombre: "mallco rancho", precio: '35-40' },
{ nombre: "alto mirador", precio: '45-50' },
{ nombre: "cuartel cotapachi", precio: '20-25' },
{ nombre: "cotapachi", precio: '30' },
{ nombre: "cercado vinto", precio: '10' },
{ nombre: "caja nacional kilometro 11", precio: '15' },
{ nombre: "caja nacional kilometro 5", precio: '30' },
{ nombre: "puente viloma", precio: '30' },
{ nombre: "montenegro", precio: '30' },
{ nombre: "machajmarca", precio: '35' },
{ nombre: "aeropuerto", precio: '60' },
{ nombre: "liriuni", precio: '100' },
{ nombre: "paucarpata", precio: '25-30' },
{ nombre: "illataco", precio: '25-30' },
{ nombre: "colegio calama", precio: '10-12' },
{ nombre: "colegio nestor adriazola", precio: '10' },
{ nombre: "colegio franz tamayo", precio: '15' },
{ nombre: "colegio teófilo vargas", precio: '15' },
{ nombre: "colegio loyola", precio: '15' },
{ nombre: "colegio martín cardenas vinto", precio: '10-12' },
{ nombre: "colegio adventista vinto", precio: '15' },
{ nombre: "colegio villa urkupiña", precio: '10' },
{ nombre: "colegio evo morales vinto", precio: '15' },
{ nombre: "colegio sagrada familia vinto", precio: '15' },
{ nombre: "colegio cerro cota", precio: '25-30' },
{ nombre: "colegio cristina prado", precio: '12' },
{ nombre: "tecnológico incos nro 3", precio: '20' },
     { nombre: "pandoja", precio: '30' }
];
